spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill
    username: root
    password: 1703649
  output:
    ansi:
      enabled: detect
mybatis:
  type-aliases-package: com.github.congyh.seckill.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    database-id: mysql
server:
  port: 8081


